name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Pull latest changes from Hugging Face Space and merge
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: "Sank21"  # Replace with your Hugging Face username
        run: |
          git remote set-url origin https://$HF_USERNAME:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Sank21/search_engine
          git config pull.rebase false  # Tell git to merge instead of rebasing
          git pull https://$HF_USERNAME:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Sank21/search_engine main
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: "Sank21"  # Replace with your Hugging Face username
        run: |
          git push https://$HF_USERNAME:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Sank21/search_engine main
