name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Debug HF_TOKEN (remove after debugging)
        run: echo "HF_TOKEN is set: ${{ secrets.HF_TOKEN }}"
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Sank21/search_engine main
